/**
 * Node filesystem adapter for the SF property ledger.
 *
 * BundleAdapter reads src/data/bundle.json + dist/r2/*.json from disk.
 * Used as the local-dev fallback when the Python CLI is unavailable.
 *
 * The Cloudflare Workers adapter (WorkerDataAdapter + R2ShardSource) lives in
 * src/worker-adapter.ts — it must stay free of node: imports so it bundles
 * for Workers. Do not re-add worker classes here.
 */
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { BundleQueryEngine, type BundleJson, type ShardSource } from "./data-engine.js";

// src/data-adapter.ts -> web/ is one level up from this file's directory.
// (Verified at runtime by scripts/verify-webroot.mjs, not by eyeball.)
export const WEB_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// bundle.json is generated by `npm run build:data`; it may not exist in a
// fresh checkout (then BundleAdapter is simply unavailable).
let bundleCache: BundleJson | null | undefined;
export function loadBundle(): BundleJson | null {
  if (bundleCache !== undefined) return bundleCache;
  const p = join(WEB_ROOT, "src", "data", "bundle.json");
  if (!existsSync(p)) {
    bundleCache = null;
    return null;
  }
  bundleCache = JSON.parse(readFileSync(p, "utf8")) as BundleJson;
  return bundleCache;
}


class FsShardSource implements ShardSource {
  constructor(private dir: string) {}
  async getObject(key: string): Promise<any | null> {
    try {
      return JSON.parse(readFileSync(join(this.dir, key), "utf8"));
    } catch {
      return null;
    }
  }
}

export class BundleAdapter extends BundleQueryEngine {
  static available(): boolean {
    return loadBundle() !== null;
  }
  constructor() {
    const b = loadBundle();
    if (!b) throw new Error("bundle.json not built — run `npm run build:data` first");
    super(b, new FsShardSource(join(WEB_ROOT, "dist", "r2")));
  }
  get modeName(): string {
    return "bundle";
  }
}
